name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use Node.js 16

    - name: Install dependencies
      run: npm install

    - name: Run Prettier and fix issues
      run: npm run prettier-fix

    - name: Run Prettier check
      run: npm run prettier-check

    - name: Run ESLint
      run: npm run lint

    - name: Run Tests
      run: npm test

      # Add a deliberate failure step
    - name: Deliberate failure step
      run: exit 1
      if: always()